GET http://localhost:8000/api/downloads/LICENSE.txt

###
GET http://localhost:8000/api/tree

###

GET http://localhost:8000/api/downloads/libraries/community/p1/All/4-bit%20Parallel%20LCD%20driver/LCD%204x20%20demo.spin

###

GET http://localhost:8000/api/downloads/docs/assets/Presentations.zip

###

GET http://localhost:8000/api/downloads/docs/assets/foobar.zip
